FROM node:20
WORKDIR /usr/src/app

# アプリケーションの依存関係をインストールする
COPY xiaovy.tvapp.web/package*.json ./xiaovy.tvapp.web/
RUN cd xiaovy.tvapp.web && npm install

# アプリケーションのソースをバンドルする
COPY xiaovy.tvapp.web ./xiaovy.tvapp.web

# アプリケーションをビルドする
RUN cd xiaovy.tvapp.web && npm run build

# ポートを開放する
EXPOSE 3000

CMD [ "npm", "--prefix", "xiaovy.tvapp.web", "run", "start", "--", "-H", "0.0.0.0"]