services:
  tvapp-web-v2:
    image: tvapp-web-v2
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    networks:
      - my-network

volumes:
    mysql-db:

networks:
  my-network:
    driver: bridge

