import { writeFile } from 'node:fs/promises';

function sqlString(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function boolInt(value) {
  return value ? 1 : 0;
}

function jsonArray(value) {
  return JSON.stringify(Array.isArray(value) ? value : []);
}

function insertMovieSql(movie) {
  const values = [
    movie.slug,
    movie.titleJa,
    movie.titleOriginal,
    movie.overview,
    movie.runtimeMin,
    movie.rating,
    jsonArray(movie.genres),
    jsonArray(movie.screeningFormats),
    movie.releaseDate,
    movie.datePrecision,
    boolInt(movie.isPostponed),
    movie.releaseScale,
    movie.theaterCount,
    boolInt(movie.nowShowing),
    movie.screeningEndDate,
    boolInt(movie.isStreamingOnly),
    movie.posterUrl,
    movie.keyvisualUrl,
    movie.contentHash,
  ].map(sqlString).join(', ');

  return `INSERT INTO movies (
  slug, title_ja, title_original, overview, runtime_min, rating,
  genres_json, screening_formats_json, release_date, date_precision,
  is_postponed, release_scale, theater_count, now_showing, screening_end_date,
  is_streaming_only, poster_url, keyvisual_url, content_hash
) VALUES (${values})
ON CONFLICT(slug) DO UPDATE SET
  title_ja=excluded.title_ja,
  title_original=excluded.title_original,
  overview=COALESCE(excluded.overview, movies.overview),
  runtime_min=COALESCE(excluded.runtime_min, movies.runtime_min),
  rating=COALESCE(excluded.rating, movies.rating),
  genres_json=excluded.genres_json,
  screening_formats_json=excluded.screening_formats_json,
  release_date=COALESCE(excluded.release_date, movies.release_date),
  date_precision=excluded.date_precision,
  is_postponed=excluded.is_postponed,
  release_scale=COALESCE(excluded.release_scale, movies.release_scale),
  theater_count=COALESCE(excluded.theater_count, movies.theater_count),
  now_showing=MAX(movies.now_showing, excluded.now_showing),
  screening_end_date=COALESCE(excluded.screening_end_date, movies.screening_end_date),
  is_streaming_only=MAX(movies.is_streaming_only, excluded.is_streaming_only),
  poster_url=COALESCE(excluded.poster_url, movies.poster_url),
  keyvisual_url=COALESCE(excluded.keyvisual_url, movies.keyvisual_url),
  content_hash=COALESCE(excluded.content_hash, movies.content_hash),
  updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now');`;
}

function insertSourceSql(movie) {
  if (!movie.source || !movie.sourceKey) return null;
  return `INSERT INTO movie_source_ids (movie_id, source, source_key, source_url)
SELECT id, ${sqlString(movie.source)}, ${sqlString(movie.sourceKey)}, ${sqlString(movie.sourceUrl)} FROM movies WHERE slug=${sqlString(movie.slug)}
ON CONFLICT(source, source_key) DO UPDATE SET movie_id=excluded.movie_id, source_url=COALESCE(excluded.source_url, movie_source_ids.source_url);`;
}

function insertCreditSql(movie, name, role, order) {
  return `INSERT OR IGNORE INTO movie_credits (movie_id, person_name, role, billing_order)
SELECT id, ${sqlString(name)}, ${sqlString(role)}, ${sqlString(order)} FROM movies WHERE slug=${sqlString(movie.slug)};`;
}

function insertNewsSql(item) {
  return `INSERT OR IGNORE INTO movie_news (
  guid, source, title, url, summary, published_at, news_category, is_forward_looking, thumbnail_url
) VALUES (${[
  item.guid,
  item.source,
  item.title,
  item.url,
  item.summary,
  item.publishedAt,
  item.category,
  1,
  item.thumbnailUrl,
].map(sqlString).join(', ')});`;
}

function insertNewsMapSql(item, slug) {
  return `INSERT OR IGNORE INTO news_movie_map (news_id, movie_id, match_method)
SELECT n.id, m.id, ${sqlString(item.matchMethod ?? 'title_match')} FROM movie_news n, movies m
WHERE n.guid=${sqlString(item.guid)} AND m.slug=${sqlString(slug)};`;
}

function insertPopularitySql(item) {
  return `INSERT INTO popularity_snapshots (movie_id, source, metric, value, snapshot_date)
SELECT id, ${sqlString(item.source)}, ${sqlString(item.metric)}, ${sqlString(item.value)}, ${sqlString(item.snapshotDate)} FROM movies WHERE slug=${sqlString(item.slug)}
ON CONFLICT(movie_id, source, metric, snapshot_date) DO UPDATE SET value=excluded.value;`;
}

export async function writeSqlFile(outFile, { runDate, source, movies, news, popularity, sourceResults = [] }) {
  const lines = [
    '-- TVapp cinema seed/upsert SQL generated by movie-crawler.',
    '-- ローカル/初回seed専用の文字列連結SQL生成。D1実行はバインドパラメータの ingest ルート経由が本経路。',
    '-- 取引文(BEGIN/COMMIT)は付けない: リモート D1 は生の BEGIN TRANSACTION を拒否するため。',
  ];

  for (const movie of movies) {
    lines.push(insertMovieSql(movie));
    const sourceSql = insertSourceSql(movie);
    if (sourceSql) lines.push(sourceSql);
    for (const director of movie.directors ?? []) lines.push(insertCreditSql(movie, director, 'director', null));
    for (const [index, actor] of (movie.cast ?? []).entries()) lines.push(insertCreditSql(movie, actor, 'cast', index + 1));
  }
  for (const item of news) {
    lines.push(insertNewsSql(item));
    for (const slug of item.relatedSlugs ?? []) lines.push(insertNewsMapSql(item, slug));
  }
  for (const item of popularity) lines.push(insertPopularitySql(item));

  const itemsSeen = movies.length + news.length + popularity.length;
  lines.push(`INSERT INTO ingest_runs (run_date, source, status, items_seen, items_upserted, message, started_at, finished_at)
VALUES (${sqlString(runDate)}, ${sqlString(source)}, ${sqlString(itemsSeen === 0 ? 'zero_rows' : 'ok')}, ${itemsSeen}, ${itemsSeen}, ${sqlString(itemsSeen === 0 ? 'Source returned zero rows' : null)}, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));`);

  for (const result of sourceResults.filter((item) => item.status === 'zero_rows')) {
    lines.push(`INSERT INTO ingest_runs (run_date, source, status, items_seen, items_upserted, message, started_at, finished_at)
VALUES (${sqlString(runDate)}, ${sqlString(result.name)}, 'zero_rows', 0, 0, 'Source returned zero rows', strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'));`);
  }
  await writeFile(outFile, `${lines.join('\n\n')}\n`, 'utf8');
}
